version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    container_name: $DB_CONTAINER_NAME
    volumes:
      - /srv/ambition/data:/var/lib/mysql
      - /srv/ambition/backup:$MYSQL_BACKUP_FOLDER
  web:
    build: .
    # command: sleep infinity
    container_name: $WEB_CONTAINER_NAME
    volumes:
      - .:/app
      - /srv/ambition/export:$DJANGO_EXPORT_FOLDER
      - /home/ambition/.etc:$DJANGO_ETC_FOLDER
      - /srv/ambition/static:$DJANGO_STATIC_ROOT
    ports:
      - 8000:8000
      - 80:80
      - 443:443
    depends_on:
      - db
