cd ~/source/ambition-ae && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-export && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-dashboard && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-labs && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-metadata-rules && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-pharmacy && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-prn && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-rando && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-reference && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-screening && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-sites && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-subject && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-validators && git add -A && git commit -m "setup files" && git push
&& cd ~/source/ambition-visit-schedule && git add -A && git commit -m "setup files" && git push
&& cd ~/source/django-collect-offline && git add -A && git commit -m "setup files" && git push
&& cd ~/source/django-collect-offline-files && git add -A && git commit -m "setup files" && git push
&& cd ~/source/django-crypto-fields && git add -A && git commit -m "setup files" && git push
&& cd ~/source/django-revision && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-action-item && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-appointment && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-base && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-consent && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-constants && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-dashboard && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-device && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-fabric && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-facility && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-fieldsets && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-fieldsets && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-form-validators && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-identifier && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-lab && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-lab-dashboard && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-label && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-list-data && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-locator && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-metadata && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-metadata-rules && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-model-admin && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-model-fields && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-model-wrapper && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-navbar && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-offstudy && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-pdutils && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-pharmacy && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-pharmacy-dashboard && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-prn && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-protocol && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-reference && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-registration && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-reportable && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-reports && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-rest && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-search && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-selenium && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-subject-dashboard && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-timepoint && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-visit-schedule && git add -A && git commit -m "setup files" && git push
&& cd ~/source/edc-visit-tracking && git add -A && git commit -m "setup files" && git push