version: '3'


services:

  db:
    image: mysql:5.7
    container_name: $DB_CONTAINER_NAME
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - /srv/$DJANGO_APP_NAME/data:/var/lib/mysql
      - /srv/$DJANGO_APP_NAME/backup:$MYSQL_BACKUP_FOLDER

  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    container_name: $WEB_CONTAINER_NAME
    # command: sleep infinity
    # command: python manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /srv/$DJANGO_APP_NAME/export:$DJANGO_EXPORT_FOLDER
      - /srv/$DJANGO_APP_NAME/.etc:$DJANGO_ETC_FOLDER
      - /srv/$DJANGO_APP_NAME/static:$DJANGO_STATIC_ROOT
      - /srv/$DJANGO_APP_NAME/log:$DJANGO_LOG_FOLDER
      - /srv/$DJANGO_APP_NAME/backup:$MYSQL_BACKUP_FOLDER
    ports:
      - 8000:8000
    depends_on:
      - db
