version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - ./app/nginx:/etc/nginx/conf.d
      - /srv/ambition/log:$DJANGO_LOG_FOLDER      
    depends_on:
      - django
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    container_name: $DB_CONTAINER_NAME
    volumes:
      - /srv/ambition/data:/var/lib/mysql
      - /srv/ambition/log:$DJANGO_LOG_FOLDER
      - /srv/ambition/backup:$MYSQL_BACKUP_FOLDER
  django:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    container_name: $WEB_CONTAINER_NAME
    volumes:
      - .:/app
      - /srv/ambition/export:$DJANGO_EXPORT_FOLDER
      - /srv/ambition/.etc:$DJANGO_ETC_FOLDER
      - /srv/ambition/static:$DJANGO_STATIC_ROOT
      - /srv/ambition/log:$DJANGO_LOG_FOLDER
      - /srv/ambition/backup:$MYSQL_BACKUP_FOLDER
    ports:
      - 8000:8000
      - 80:80
      - 443:443
    depends_on:
      - db
      